#NUMPY BASICS

#CREATING A NUMPY ARRAY AND ITS ATTRRIBUTES

In [ ]:
#importing numpy library
import numpy as np
#creating a list
my_list=[1,2,3,4,5]
#changing the list into a numpy array
my_array=np.array(my_list)
#printing the array
print(my_array)

#creating a 0-D numpy array
zero_array=np.array(42)
#printing the array
print(zero_array)

#Instead of creating a list on a asepearet varaible we can directly pass a list to .array(function) like this:
my_array=np.array([1,2,3,4,5])
#printing the 1-D numpy array
print(my_array)

#lets create a 2-D array!
two_d_array=np.array([[1,2,3],[4,5,6]])
#printing the 2-D numpy array
print(two_d_array)

#lets create a 3-D array now!
three_d_array=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
#printing the 3-D numpy array
print(three_d_array)

[1 2 3 4 5]
42
[1 2 3 4 5]


In [ ]:
#lets create abd erray and see its attributes!
my_array = np.array([[1,2,3],[4,5,6]])
print(my_array) #Printing the array
print(my_array.ndim)  #Printing the dimesnsion of the array
print(my_array.shape) #Printing the shape of the array
print(my_array.dtype) #Printing the type of the array
print(my_array.size) #Printing the size of the array


[[1 2 3]
 [4 5 6]]
2
(2, 3)
int64
6


#ACCESSING AND MANIPULATING ARRAY ELEMENTS

In [ ]:
#lets create a 1-D array and print one of its elements
one_arr = np.array([1,2,3,4,5,6])
print(one_arr[4])

#lets print using negative indexing
print(one_arr[-3])

5
4


In [ ]:
#lets create a 2-D array
two_arr = np.array([[1,2,3],[4,5,6]])
print(two_arr[1,2])
print(two_arr[0,-1])


6
3


In [ ]:
#lets move to a 3-D array
three_arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(three_arr[1,1,2])
print(three_arr[1,0,0])

12
7


#SLICING ARRAYS

### Some Important Slicing Concepts
array[start.end]

array[start:end:steps]

In [ ]:
#Slicing array from 0th index to 8th index
my_array = np.array([1,2,3,4,5,6,7,8,9,10])
print(my_array[0:8])


[1 2 3 4 5 6 7 8]


In [ ]:
#Slicing with steps
my_new_array = np.array([1,2,3,4,5,6,7,8,9,10])
print(my_new_array[0:9:2])

[1 3 5 7 9]


In [ ]:
#Slicing on a 2-D array
my_two_d = np.array([[1,2,3,4,5,6,7,8,9],[10,11,12,13,14,15,16,17,18]])
print(my_two_d[1,0:6])
print(my_two_d[0,3:6])

[10 11 12 13 14 15]
[4 5 6]


#Homework: Experiment with slicing on a 3-D Array
#

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#CLASSWORK

1. Create a NumPy array from the list [7, 14, 21, 28]. Print the array.


In [ ]:
import numpy as np
my_list=[7,14,21,28]
print(my_list)

[7, 14, 21, 28]


In [ ]:
two_d_array=np.array([[5,10,15],[20,25,30]])
print(my_array.shape)
print(my_array.ndim)

(10,)
1


3. Use np. zeros to create a 2D array of shape (2, 3). Then, use np. arange to create an array from 0 to 12 with a step of 3. Print both arrays


In [ ]:
import numpy as np
np.zeros((2,3))
arr = np.arange(0,13,3)
print(arr)

[ 0  3  6  9 12]


4. Create a NumPy array (2, 4, 6, 8]. Multiply all elements by 3 and print the result.


In [ ]:
import numpy as np
arr = np.array([2,4,6,8])
result = arr * 3
print(result)


[ 6 12 18 24]


5. Create a NumPy array [1, 3, 5, 7, 9, 11]. Print the third element and a slice from index 1 to 3 (inclusive).

In [ ]:
import numpy as np
arr = np.array([1,3,5,7,9,11])
print("Third Element is:", arr[2])
print(arr[1:4])


Third Element is: 5
[3 5 7]


 Task 1: Create a 1D NumPy array with even numbers from 2 to 10 (inclusive), add 5 to each element

In [ ]:
import numpy as np
arr = np.arange(2,11,2)
print(arr)
result = arr + 5
print(result)

[ 2  4  6  8 10]
[ 7  9 11 13 15]


# Task 2: Create a 2D array with shape (2, 3) with values [[1,3,5], [2,4,6]].Extract first row and compute its sum using np.sum. Print both the first row and the sum.

In [ ]:
array2 = np.array([[1, 3, 5], [2, 4, 6]])
print(array2[0])
print(np.sum(array2[0]))

[1 3 5]
9


1. Create a 2D NumPy array of shape (3, 3) with random integers between 1 and 10 (inclusive) using np. random. randint. Then, replace all values greater than 5 with 0 and print the modified array.


In [6]:
import numpy as np
arr = np.random.randint(1, 11, size=(3, 3))
arr[arr > 5] = 0 # Replace values greater than 5 with 0
print(arr)

[[2 4 3]
 [0 0 0]
 [1 0 0]]


Create two 1D NumPy arrays: [2, 4, 6, 8] and [1, 3, 5, 7]. Compute the element-wise sum and the dot product of the two arrays. Print both results.


In [7]:
import numpy as np
arr1 = np.array([2, 4, 6, 8])
arr2 = np.array([1, 3, 5, 7])
sum_arr = arr1 + arr2
dot_arr = np.dot(arr1, arr2)
print(sum_arr)
print(dot_arr)

[ 3  7 11 15]
100


Create a 2D NumPy array of shape (4, 3) filled with ones using np.ones. Then, add a 1D array [10, 20, 30] to each row of the 2D array using broadcasting. Print the resulting array.


In [8]:
import numpy as np
two_d_array = np.ones((4, 3))
one_d_array = np.array([10, 20, 30])
result = two_d_array + one_d_array
print(result)

[[11. 21. 31.]
 [11. 21. 31.]
 [11. 21. 31.]
 [11. 21. 31.]]


Create a 2D NumPy array [[1, 2, 3], [4, 5, 6], [7, 8, 9]] . Extract the second column and compute its mean using p.mean. Then, reshape the original array into a 1D array and print both results.


In [10]:
import numpy as np
two_d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
second_column = two_d_array[:, 1]
print(second_column)
mean_second_column = np.mean(second_column)
print(mean_second_column)
one_d_array = two_d_array.flatten()
print(one_d_array)


[2 5 8]
5.0
[1 2 3 4 5 6 7 8 9]


Create a 1D NumPy array [10, 20, 30, 40, 50, 60] . Use a boolean mask to select elements greater than 30, then square those elements. Print the original array and the modified array.

In [11]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60])
boolean_mask = arr > 30
modified_arr = arr[boolean_mask]**2
print(arr)
print(modified_arr)

[10 20 30 40 50 60]
[1600 2500 3600]
